version: "3.9"
services:
  backend:
    build: src/backend/
    volumes:
      - ./persist/:/service/persist:rw
  proxy:
    build: src/proxy/
    links:
      - "backend:backend"
    ports:
      - "4433:4433/udp"
  interface:
    build: src/interface
    links:
      - "proxy:proxy"
    ports:
      - "4420:4420"
