version: '3'
services:
  # Give your container proper names!
  steinsgate-checker:
    build: .
    # The checker runs a HTTP interfaces, so we need to map port 3031 to the outside (port 8000).
    ports:
      - 8000:3031
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=steinsgate-mongo
     - MONGO_PORT=27017
     - MONGO_USER=steinsgate_checker
     - MONGO_PASSWORD=steinsgate_checker

  # The python checkerlib requires a mongo db!
  steinsgate-mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: steinsgate_checker
      MONGO_INITDB_ROOT_PASSWORD: steinsgate_checker